# kubectl apply -f deployment.yml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: santiagoprada-deployment
  namespace: santiagoprada-namespace
spec:
  replicas: 2
  selector:
    matchLabels:
      app: microservice
  template:
    metadata:
      labels:
        app: microservice
    spec:
      containers:
      - name: microservice
        image: santiagoprada1029/santiago-prada:v3